apiVersion: v1
kind: Pod
metadata:  
  name: pod-with-configmap
spec:
  containers:
  - image: fpommerening/container-training:webapp-v1
    name: app
    envFrom:
    - configMapRef:
        name: my-configmap
