apiVersion: batch/v1
kind: Job
metadata:
  name: my-onetime-job
spec:
  template:
    spec:
      containers:
      - name: app
        image: busybox:1.28
        command: ["sh", "-c", "echo The app is running! && sleep 45 && echo The work is done!"]
      restartPolicy: OnFailure
