apiVersion: v1
kind: Service
metadata:
  name: node-port-svc
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name: welcome-http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080